#!/usr/bin/env bash
# CELLM — Bootstrap boundary.yml for a project
# Scans project structure and generates an initial boundary.yml declaration.
# Invoked by /cellm:init skill, NOT by hooks.
#
# Input: JSON via stdin { "cwd": "/path/to/project" }
# Output: boundary.yml in the project root (idempotent — skips if exists)

set -euo pipefail

LOG_FILE="${HOME}/.cellm/logs/bootstrap-boundaries.log"
mkdir -p "$(dirname "${LOG_FILE}")"

log() {
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [Bootstrap] $1" >> "${LOG_FILE}" 2>/dev/null || true
}

# Read JSON from stdin
input=""
if [[ ! -t 0 ]]; then
  input=$(head -c 65536)
fi

# Parse cwd
cwd=""
if [[ -n "${input}" ]] && command -v jq &>/dev/null; then
  cwd=$(echo "${input}" | jq -r '.cwd // ""')
fi
cwd="${cwd:-${PWD}}"

# Resolve to git root if possible
if command -v git &>/dev/null; then
  git_root=$(cd "${cwd}" 2>/dev/null && git rev-parse --show-toplevel 2>/dev/null || echo "")
  if [[ -n "${git_root}" ]]; then
    cwd="${git_root}"
  fi
fi

boundary_file="${cwd}/boundary.yml"

# Idempotent: skip if boundary.yml already exists
if [[ -f "${boundary_file}" ]]; then
  log "boundary.yml already exists at ${boundary_file}, skipping"
  echo '{"status":"skipped","reason":"boundary.yml already exists"}'
  exit 0
fi

project_name=$(basename "${cwd}")
log "Scanning project: ${project_name} at ${cwd}"

# --- Component Discovery ---

components=()
component_paths=()

# Strategy 1: npm/bun workspaces from root package.json
if [[ -f "${cwd}/package.json" ]] && command -v jq &>/dev/null; then
  workspaces=$(jq -r '.workspaces[]? // empty' "${cwd}/package.json" 2>/dev/null || true)
  if [[ -n "${workspaces}" ]]; then
    while IFS= read -r ws; do
      # Expand glob patterns (e.g., "packages/*")
      for ws_dir in ${cwd}/${ws}; do
        if [[ -d "${ws_dir}" && -f "${ws_dir}/package.json" ]]; then
          rel_path="${ws_dir#"${cwd}/"}"
          comp_name=$(basename "${ws_dir}")
          components+=("${comp_name}")
          component_paths+=("${rel_path}/")
          log "Found workspace: ${comp_name} (${rel_path}/)"
        fi
      done
    done <<< "${workspaces}"
  fi
fi

# Strategy 2: Directories with package.json (if no workspaces found)
if [[ ${#components[@]} -eq 0 ]]; then
  while IFS= read -r pkg_json; do
    dir=$(dirname "${pkg_json}")
    rel_path="${dir#"${cwd}/"}"
    # Skip root, node_modules, hidden dirs, and deep nesting (max 2 levels)
    if [[ "${rel_path}" == "." || "${rel_path}" == "${cwd}" ]]; then
      continue
    fi
    if [[ "${rel_path}" == *node_modules* || "${rel_path}" == .* ]]; then
      continue
    fi
    depth=$(echo "${rel_path}" | tr '/' '\n' | wc -l | tr -d ' ')
    if [[ "${depth}" -gt 2 ]]; then
      continue
    fi
    comp_name=$(basename "${dir}")
    components+=("${comp_name}")
    component_paths+=("${rel_path}/")
    log "Found sub-package: ${comp_name} (${rel_path}/)"
  done < <(find "${cwd}" -maxdepth 3 -name "package.json" -not -path "*/node_modules/*" -not -path "*/.git/*" 2>/dev/null | sort)
fi

# Strategy 3: Cargo workspaces
if [[ -f "${cwd}/Cargo.toml" ]] && command -v grep &>/dev/null; then
  in_members=false
  while IFS= read -r line; do
    if [[ "${line}" =~ ^\[workspace\] ]]; then
      in_members=false
    fi
    if [[ "${line}" =~ members ]]; then
      in_members=true
      continue
    fi
    if ${in_members}; then
      if [[ "${line}" == "]" ]]; then
        break
      fi
      member=$(echo "${line}" | tr -d ' ",' | sed 's/#.*//')
      if [[ -n "${member}" && -d "${cwd}/${member}" ]]; then
        comp_name=$(basename "${member}")
        components+=("${comp_name}")
        component_paths+=("${member}/")
        log "Found Cargo workspace: ${comp_name} (${member}/)"
      fi
    fi
  done < "${cwd}/Cargo.toml"
fi

# Strategy 4: Go modules (go.work)
if [[ -f "${cwd}/go.work" ]]; then
  while IFS= read -r line; do
    trimmed=$(echo "${line}" | tr -d ' \t')
    if [[ -n "${trimmed}" && "${trimmed}" != "use(" && "${trimmed}" != ")" && "${trimmed}" != go* ]]; then
      if [[ -d "${cwd}/${trimmed}" ]]; then
        comp_name=$(basename "${trimmed}")
        components+=("${comp_name}")
        component_paths+=("${trimmed}/")
        log "Found Go module: ${comp_name} (${trimmed}/)"
      fi
    fi
  done < "${cwd}/go.work"
fi

# --- Generate boundary.yml ---

{
  cat <<'HEADER'
# boundary.yml — Architectural Boundary Declaration
# Generated by cellm bootstrap. Customize provides/depends/forbidden per component.
# Docs: https://cellm.dev/docs/boundary

apiVersion: boundary/v1

components:
HEADER

  if [[ ${#components[@]} -eq 0 ]]; then
    # No components discovered — generate a single-component default
    cat <<SINGLE

  ${project_name}:
    path: ./
    provides: []
    depends: []
    forbidden: []
    tags:
      - "scope:root"
SINGLE
    log "No sub-components found, generated single-component boundary"
  else
    for i in "${!components[@]}"; do
      name="${components[$i]}"
      path="${component_paths[$i]}"
      # Sanitize component name for YAML key (lowercase, replace special chars)
      safe_name=$(echo "${name}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
      cat <<COMPONENT

  ${safe_name}:
    path: ${path}
    provides: []
    depends: []
    forbidden: []
    tags: []
COMPONENT
    done
  fi
} > "${boundary_file}"

comp_count=${#components[@]}
if [[ ${comp_count} -eq 0 ]]; then
  comp_count=1
fi

log "Generated boundary.yml with ${comp_count} component(s)"
echo "{\"status\":\"created\",\"file\":\"${boundary_file}\",\"components\":${comp_count}}"
exit 0
